### ISSUE TITLE
R or Python Version

### ISSUE THREAD

**Issue by rfarouni** [xuranw/locCSN#1]
Hi,

Are there any plans to have the code implemented in R or Python?
Thanks!

**Comment by xuranw** [comment]
Please see functions the Python file. If you have any suggested tutorial for publish python packages on github, please tell me. I have trouble packing functions.

**Comment by rfarouni** [comment]
Hi Xuran,

Thanks for uploading the code. Since most labs in single cell RNA-seq community use R or Python for analysis, I am curious to know why Matlab was chosen.  At any rate, if you take the Python option, then it would be great if  the package can interoperate with scanpy (https://scanpy.readthedocs.io/en/stable/). For example, if your data loading function can take an AnnData object (http://falexwolf.de/blog/171223_AnnData_indexing_views_HDF5-backing/). This way, users can load  large files without problems. If you choose the R option, then I recommend creating a biocoductor package that takes in data as a SingleCellExperiment object.  Another option is Julia, an open source alternative to Matlab which is gaining popularity in many fields.

Here is a standard tutorial for packaging https://packaging.python.org/tutorials/packaging-projects/

For a good resource on bioconductor packages see here http://bioconductor.org/books/release/OSCA/

Great work. Thanks once again!

Rick,

**Comment by chenxofhit** [comment]
Thanks for the great work！

**Comment by xuranw** [comment]
Now we have Python version!
